const users = [
    {
        id: 1,
        username: "n4nd0",
        password: "12345",
        fullName: "Hernando",
    },
    {
        id: 2,
        username: "r4ff1",
        password: "12345",
        fullName: "Raffi",
    },
    {
        id: 3,
        username: "w1r4",
        password: "12345",
        fullName: "Wira",
    },
]

// const products = [
//     {
//         id : 1,
//         productName: "iPhone X",
//         condition: "perfect",
//         harga: 10000000,
//     },
//     {
//         id : 2,
//         productName: "iPhone 11",
//         condition: "good",
//         harga: 13000000,
//     },
//     {
//         id : 3,
//         productName: "iPhone 12",
//         condition: "fair",
//         harga: 15000000,
//     },
// ]

const products = {
    "iphone-11": [
        {
            id : 1,
            type: "iphone-11",
            name : "iPhone 11 64GB - Black",
            color: "black",
            condition : "good",
            price: 6000000,
            storage: 64,
            image: "https://cdn.eraspace.com/media/catalog/product/a/p/apple_iphone_11_black_new_1_6_2.jpg",
        },
        {
            id : 2,
            type: "iphone-11-pro",
            name : "iPhone 11 Pro 128GB - White",
            color: "white",
            condition : "excellent",
            price: 7000000,
            storage: 128,
            image: "https://cdn.eraspace.com/media/catalog/product/a/p/apple_iphone_11_white_new_1_7.jpg", 
        },
        {
            id : 3,
            type: "iphone-11-pro-max",
            name : "iPhone 11 Pro Max 516GB - Green",
            color: "green",
            condition : "good",
            price: 5500000,
            storage: 516,
            image: "https://cdn.eraspace.com/media/catalog/product/a/p/apple_iphone_11_pro_midnight_green_new_1_4.jpg",
        },
    ],
    "iphone-12": [
        {
            id : 4,
            type: "iphone-12-mini",
            name : "iPhone 12 Mini 64GB - Purple",
            color: "purple",
            condition : "excellent",
            price: 11299000,
            storage: 64,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_12_mini_purple_1_2.jpg",
        },
        {
            id : 5,
            type: "iphone-12",
            name : "iPhone 12 128GB - Red",
            color: "red",
            condition : "good",
            price: 12499000,
            storage: 128,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_12_product_red_1_4_1.jpg",
        },
        {
            id : 6,
            type: "iphone-12-pro",
            name : "iPhone 12 Pro 516GB - Graphite",
            color: "graphite",
            condition : "excellent",
            price: 10999000,
            storage: 516,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_12_pro_graphite_1_1_2.jpg",
        },
        {
            id : 7,
            type: "iphone-12-pro-max",
            name : "iPhone 12 Pro Max 516GB - Silver",
            color: "silver",
            condition : "excellent",
            price: 10999000,
            storage: 516,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_12_pro_max_silver_1_1.jpg",
        },
    ],
    "iphone-13": [
        {
            id : 8,
            type: "iphone-13-mini",
            name : "iPhone 13 Mini 64GB - Pink",
            color: "pink",
            condition : "good",
            price: 8799000,
            storage: 64,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_13_mini_pink_1_4_1.jpg",
        },
        {
            id : 9,
            type: "iphone-13",
            name : "iPhone 13 128GB - Midnight",
            color: "midnight",
            condition : "good",
            price: 8799000,
            storage: 128,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_13_midnight_1_4_1.jpg",
        },
        {
            id : 10,
            type: "iphone-13-pro",
            name : "iPhone 13 Pro 256GB - Silver",
            color: "silver",
            condition : "excellent",
            price: 15999000,
            storage: 256,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_13_pro_silver_1_6_1.jpg",
        },
        {
            id : 11,
            type: "iphone-13-pro-max",
            name : "iPhone 13 Pro Max 512GB - Gold",
            color: "gold",
            condition : "good",
            price: 19499000,
            storage: 512,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_13_pro_gold_1_5_1.jpg",
        },
    ],
    "iphone-14": [
        {
            id : 12,
            type: "iphone-14-mini",
            name : "iPhone 14 Mini 128GB - Yellow",
            color: "yellow",
            condition : "excellent",
            price: 9999000,
            storage: 128,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_14_yellow_1_7.jpg",
        },
        {
            id : 13,
            type: "iphone-14",
            name : "iPhone 14 256GB - Purple",
            color: "purple",
            condition : "good",
            price: 13299000,
            storage: 256,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_14_purple_1_1_2.jpg",
        },
        {
            id : 14,
            type: "iphone-14-pro",
            name : "iPhone 14 Pro 512GB - Silver",
            color: "silver",
            condition : "excellent",
            price: 17999000,
            storage: 512,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_14_pro_silver_1_1_3.jpg",
        },
        {
            id : 15,
            type: "iphone-14-pro-max",
            name : "iPhone 14 Pro Max 512GB - Gold",
            color: "gold",
            condition : "good",
            price: 20999000,
            storage: 512,
            image: "https://cdn.eraspace.com/media/catalog/product/i/p/iphone_14_pro_gold_1_5.jpg",
        },
    ],
}
export { users, products }
